version: "3.7"

services:
  app:
    image: getting-started
    build:
      context: ./getting-started
      dockerfile: ./Dockerfile
    ports:
      - 3454:80
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--debug", "--port", "80", "--reload-dir", "/app"]
    volumes:
      - /Users/user/Downloads/data/config/vpnnanny:/app
      - /private/etc/vpns:/vpns
